version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ai-tweet-generate"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pccegsgknfet"
s3_prefix = "ai-tweet-generate"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
